- name: play dockercoins
  hosts: 192.168.205.10
  gather_facts: no
  tasks:
    - name: Copy dockercoins.yaml on master
      copy: src=dockercoins.yaml dest=/home/vagrant/ owner=vagrant group=vagrant mode=0644
    - name: Sleep 30 sec
      command: sleep 60
    - name: Deploy dockercoins
      command: kubectl apply -f dockercoins.yaml

